#!/usr/bin/env python3
"""
Calibrate Lambda_EDE_ridder to match target Omega_Lambda in freeze mode.

This finds the Lambda value such that a frozen Ridder field exactly
reproduces the standard ΛCDM dark energy density at z=0.

Usage:
    python calibrate_lambda_lcdm.py --target 0.69 --tolerance 0.001
"""

import subprocess
import re
import sys
import os
from pathlib import Path

def write_ini_file(lambda_eV, theta_i=1.5, output_path="test_lambda_trial.ini"):
    """Write a CLASS ini file with given Lambda value."""
    ini_content = f"""# Lambda Calibration Trial
# Auto-generated by calibrate_lambda_lcdm.py

H0 = 67.36
omega_b = 0.02237
omega_cdm = 0.1200
A_s = 2.1e-9
n_s = 0.9649
tau_reio = 0.0544
YHe = 0.2454
gauge = newtonian

# Ridder field in freeze mode
Lambda_EDE_ridder = {lambda_eV:.6e}
f_axion_ridder = 2.435e27
theta_i_ridder = {theta_i:.6f}
beta_ridder = 0.0
n_ridder = 3
ridder_c_slow = 0.0

ridder_freeze_phi = yes
ridder_force_damping = 0.0
use_ridder_shooting = 0

output = 
write background = no
"""
    
    with open(output_path, 'w') as f:
        f.write(ini_content)
    
    return output_path

def run_class_and_extract_f_ridder(ini_file, class_executable="./phase2/class/class", timeout=60):
    """
    Run CLASS with given ini file and extract f_ridder at a=1.
    
    Returns:
        float: f_ridder value, or None if failed
    """
    try:
        result = subprocess.run(
            [class_executable, ini_file],
            capture_output=True,
            text=True,
            timeout=timeout
        )
        
        # Try method 1: Look for our clean diagnostic line
        # Format: "  f_ridder   = 1.234567e-02 (fraction of total)"
        pattern1 = r'f_ridder\s*=\s*([\d.e+-]+)\s*\(fraction'
        match1 = re.search(pattern1, result.stdout)
        
        if match1:
            f_ridder = float(match1.group(1))
            return f_ridder
        
        # Method 2: Parse the last debug line before crash/completion
        # Format: "RIDDER DEBUG (adding to rho_tot): a=X, rho_ridder=Y, rho_tot_before=Z, rho_tot_after=W"
        # Find the line with largest 'a' value (closest to a=1)
        pattern2 = r'RIDDER DEBUG.*a=([\d.e+-]+).*rho_ridder=([\d.e+-]+).*rho_tot_after=([\d.e+-]+)'
        matches = re.findall(pattern2, result.stdout)
        
        if matches:
            # Get the last match (latest time)
            a_val, rho_ridder, rho_tot = matches[-1]
            a_val = float(a_val)
            rho_ridder = float(rho_ridder)
            rho_tot = float(rho_tot)
            
            if rho_tot > 0:
                f_ridder = rho_ridder / rho_tot
                return f_ridder
        
        print(f"Warning: Could not extract f_ridder from output")
        return None
            
    except subprocess.TimeoutExpired:
        print(f"ERROR: CLASS run timed out after {timeout}s")
        return None
    except Exception as e:
        print(f"ERROR running CLASS: {e}")
        return None

def bisect_lambda(target_f, theta_i=1.5, tolerance=0.001, max_iterations=25):
    """
    Bisection search to find Lambda that gives target f_ridder.
    
    Args:
        target_f: Target f_ridder value (e.g., 0.69 for full Omega_Lambda)
        theta_i: Initial field angle (radians, as multiple of f_axion)
        tolerance: Acceptable error in f_ridder
        max_iterations: Maximum bisection steps
    
    Returns:
        tuple: (best_lambda, achieved_f, iterations)
    """
    
    # Initial bracket based on analytic estimate
    # We know Lambda ~ 9e-4 gives f ~ 7e-11
    # We want f ~ 0.69, so scale by (0.69/7e-11)^(1/4) ~ 316
    log10_lambda_low = -3.0   # 1e-3 eV (below target)
    log10_lambda_high = 1.0    # 10 eV (above target)
    
    print("=" * 60)
    print("Lambda Calibration for ΛCDM Recovery (Freeze Mode)")
    print("=" * 60)
    print(f"Target: f_ridder = {target_f:.6f} ± {tolerance:.6f}")
    print(f"theta_i = {theta_i:.6f} rad")
    print(f"Initial bracket: log10(Lambda/eV) ∈ [{log10_lambda_low:.2f}, {log10_lambda_high:.2f}]")
    print()
    
    # Evaluate bracket endpoints
    print("Evaluating bracket endpoints...")
    lambda_low = 10**log10_lambda_low
    f_low = run_class_and_extract_f_ridder(write_ini_file(lambda_low, theta_i))
    if f_low is None:
        print("ERROR: Failed to evaluate lower bracket")
        return None, None, 0
    
    lambda_high = 10**log10_lambda_high
    f_high = run_class_and_extract_f_ridder(write_ini_file(lambda_high, theta_i))
    if f_high is None:
        print("ERROR: Failed to evaluate upper bracket")
        return None, None, 0
    
    print(f"  Lambda = {lambda_low:.6e} eV → f = {f_low:.6e}")
    print(f"  Lambda = {lambda_high:.6e} eV → f = {f_high:.6e}")
    print()
    
    # Check bracket validity
    if (f_low - target_f) * (f_high - target_f) > 0:
        print("ERROR: Bracket does not contain target!")
        print(f"  Both endpoints on same side: f_low - target = {f_low - target_f:.3e}, f_high - target = {f_high - target_f:.3e}")
        print("  Adjust bracket or check CLASS behavior")
        return None, None, 0
    
    # Bisection loop
    print("Starting bisection...")
    print(f"{'Iter':<6} {'log10(Λ)':<12} {'Lambda/eV':<14} {'f_ridder':<14} {'Error':<14} {'Status':<10}")
    print("-" * 80)
    
    for iteration in range(max_iterations):
        # Midpoint
        log10_lambda_mid = 0.5 * (log10_lambda_low + log10_lambda_high)
        lambda_mid = 10**log10_lambda_mid
        
        # Evaluate
        f_mid = run_class_and_extract_f_ridder(write_ini_file(lambda_mid, theta_i))
        if f_mid is None:
            print(f"ERROR: Failed at iteration {iteration}")
            return None, None, iteration
        
        error = f_mid - target_f
        status = "converged" if abs(error) < tolerance else "continue"
        
        print(f"{iteration:<6} {log10_lambda_mid:<12.6f} {lambda_mid:<14.6e} {f_mid:<14.6e} {error:<+14.6e} {status:<10}")
        
        # Check convergence
        if abs(error) < tolerance:
            print()
            print("=" * 60)
            print("CONVERGED!")
            print(f"  Lambda = {lambda_mid:.6e} eV")
            print(f"  f_ridder = {f_mid:.6f}")
            print(f"  Error = {error:+.6f} (target ± {tolerance})")
            print(f"  Iterations = {iteration + 1}")
            print("=" * 60)
            return lambda_mid, f_mid, iteration + 1
        
        # Update bracket
        if (f_low - target_f) * error < 0:
            # Root is in [low, mid]
            log10_lambda_high = log10_lambda_mid
            f_high = f_mid
        else:
            # Root is in [mid, high]
            log10_lambda_low = log10_lambda_mid
            f_low = f_mid
    
    print()
    print("WARNING: Did not converge within max iterations")
    print(f"  Best result: Lambda = {lambda_mid:.6e} eV, f = {f_mid:.6f}, error = {error:+.6f}")
    return lambda_mid, f_mid, max_iterations

def main():
    import argparse
    
    parser = argparse.ArgumentParser(description="Calibrate Lambda for ΛCDM recovery")
    parser.add_argument('--target', type=float, default=0.69,
                        help='Target f_ridder value (default: 0.69 for Omega_Lambda)')
    parser.add_argument('--theta-i', type=float, default=1.5,
                        help='Initial field angle in radians (default: 1.5, use 3.14159 for extremum)')
    parser.add_argument('--tolerance', type=float, default=0.001,
                        help='Acceptable error in f_ridder (default: 0.001)')
    parser.add_argument('--max-iter', type=int, default=25,
                        help='Maximum bisection iterations (default: 25)')
    parser.add_argument('--class-exe', type=str, default='./phase2/class/class',
                        help='Path to CLASS executable')
    
    args = parser.parse_args()
    
    # Check CLASS executable exists
    if not os.path.exists(args.class_exe):
        print(f"ERROR: CLASS executable not found: {args.class_exe}")
        print("Build CLASS first or specify correct path with --class-exe")
        sys.exit(1)
    
    # Run calibration
    lambda_best, f_best, iterations = bisect_lambda(
        target_f=args.target,
        theta_i=args.theta_i,
        tolerance=args.tolerance,
        max_iterations=args.max_iter
    )
    
    if lambda_best is not None:
        # Write final calibrated ini file
        theta_label = f"theta{args.theta_i:.4f}".replace('.', 'p')
        final_ini = f"test_lcdm_recovery_calibrated_{theta_label}.ini"
        write_ini_file(lambda_best, args.theta_i, final_ini)
        print()
        print(f"Calibrated configuration saved to: {final_ini}")
        print()
        print("Next steps:")
        print(f"  1. Run: {args.class_exe} {final_ini}")
        print("  2. Verify H(z), age, and Omega's match ΛCDM baseline")
        print("  3. Use this Lambda as anchor for EDE parameter scans")
        
        return 0
    else:
        print("\nCalibration FAILED")
        return 1

if __name__ == '__main__':
    sys.exit(main())

