
# ΛCDM control for validation
H0 = 67.36
omega_b = 0.02237
omega_cdm = 0.1200
A_s = 2.1e-9
n_s = 0.9649
tau_reio = 0.0544
YHe = 0.2454

use_ridder = no

output = 
write background = yes
background_verbose = 1
write parameters = yes
root = output/validate_lcdm_control_
