# Debug Ridder Field with High Lambda
root = output/debug_max_
write background = yes
write parameters = yes
background_verbose = 2

# Cosmological parameters
h = 0.67
T_cmb = 2.7255
Omega_b = 0.05
Omega_cdm = 0.26
N_ur = 3.046

# Ridder parameters
Lambda_EDE_ridder = 3.0
f_axion_ridder = 1.e26
theta_i_ridder = 2.5
n_ridder = 3
beta_ridder = 0.0

# Output
output = tCl,pCl,lCl
modes = s
lensing = yes
