
# Ridder Field Scan
# Lambda_EDE = 1.5

root = output/scan_1.50_
output = tCl,pCl,lCl,mPk
lensing = yes
gauge = newtonian  # Force Newtonian for DM coupling
modes = s
l_max_scalars = 2500
P_k_max_h/Mpc = 1.0
z_pk = 0

# Cosmological parameters
h = 0.6736
T_cmb = 2.7255
omega_b = 0.02237
omega_cdm = 0.1200
# Omega_Lambda = 0.6911 <-- REMOVED to let CLASS fill with Lambda
Omega_fld = 0.0         # <-- Force fld to 0 to prevent ghost fluid filling


# Ridder Field
Lambda_EDE_ridder = 1.5
f_axion_ridder = 1e27
theta_i_ridder = 2.8
beta_ridder = 0.01
n_ridder = 3

# Primordial
A_s = 2.1e-9
n_s = 0.9665
tau_reio = 0.0561

# Precision
background_verbose = 1
thermodynamics_verbose = 1
write background = yes

