
# Ridder Field Scan
# Lambda_EDE = 0.8888888888888888

output = tCl,pCl,lCl,mPk
lensing = yes
modes = s
l_max_scalars = 2500
P_k_max_h/Mpc = 1.0
z_pk = 0

# Cosmological parameters
h = 0.6736
T_cmb = 2.7255
omega_b = 0.02237
omega_cdm = 0.1200
Omega_Lambda = 0.6911

# Ridder Field
Lambda_EDE_ridder = 0.8888888888888888
f_axion_ridder = 1e16
theta_i_ridder = 2.0
beta_ridder = 0.0
n_ridder = 3

# Primordial
A_s = 2.1e-9
n_s = 0.9665
tau_reio = 0.0561

# Precision
background_verbose = 1
